### PR TITLE
Binary has (misplaced) AVX512 instructions

### LINKED ISSUE #9: Error: No command specified  See ‘flatpak --help’
so when i insatalled it with flathub then ran the command to run it nothing happens. then i click on it in my chrome os tab and it brings me to linux terminal loads then says

Error: No command specified

See ‘flatpak --help’

and i dont understand what to do now?

### PR DESCRIPTION
**Pull request by ghost**
Temporary workaround. Do not merge yet, but I might use it temporarily as a fix.

The gcc version used to build the flatpak emmits AVX512 instructions before the CPU fallback chain acts. This is a workaround to resolve the issue. Let's hear from CI.

Closes #9.

### CODE REVIEW

**Comment by claudioandre-br** [comment]
Fallback chain works fine now:

```
$ OMP_NUM_THREADS=1 flatpak run com.openwall.John --test=0

Testing: descrypt, traditional crypt(3) [DES 256/256 AVX2]... PASS
[...]
Testing: dummy [N/A]... PASS
Testing: crypt, generic crypt(3) [?/64]... PASS
All 423 formats passed self-tests!
```

```
$ flatpak run com.openwall.John --test=0 --format=sha*

Will run 8 OpenMP threads
Testing: sha1crypt, NetBSD's sha1crypt [PBKDF1-SHA1 256/256 AVX2 8x]... (8xOMP) PASS
Testing: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 256/256 AVX2 8x]... (8xOMP) PASS
Testing: sha512crypt, crypt(3) $6$ (rounds=5000) [SHA512 256/256 AVX2 4x]... (8xOMP) PASS
All 3 formats passed self-tests!
```

```
$ flatpak info com.openwall.John 

John the Ripper CE - John the Ripper "Jumbo" password cracker
[...]
    Versão: 1.9J1+2310.1
```

I'll probably merge while upstream finds a permanent solution.

**Comment by sleepy124** [comment]
doesnt work still sighan364@penguin:~$ MP_NUM_THREADS=1 flatpak run com.openwall.John --test=0
sighan364@penguin:~$ flatpak run com.openwall.John --test=0 --format=sha*
sighan364@penguin:~$ flatpak info com.openwall.John 

John the Ripper CE - John the Ripper "Jumbo" password cracker

          ID: com.openwall.John
         Ref: app/com.openwall.John/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.9J1+
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 144.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 481899b3317624a1a9df5ff202a8ec38b7748baa0bc9d0e4156203b8771ce824
      Parent: f71957763afd5920c47f8b7b0c1a6fbd41ab1058c2dfd3bc65a4b8a9b02f0425
     Subject: maint: update SIMD extensions generated by build (18336d79)
        Date: 2023-09-27 15:13:39 +0000
sighan364@penguin:~$

**Comment by claudioandre-br** [comment]
To update it, run:
```
$ flatpak update com.openwall.John

Looking for updates?


        ID                         Branch         Op         Remote          Download
 1. [?] com.openwall.John          stable         u          flathub         23.4?MB / 72.3?MB

Updates complete.


$ flatpak info com.openwall.John  # Confirm it was updated

John the Ripper CE - John the Ripper "Jumbo" password cracker

          ID: com.openwall.John
         Ref: app/com.openwall.John/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.9J1+2310.1
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 144.3?MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: bb031fbfcccd6236fe8e1ca6501a0134f340d303a2af195cbe018fb13ff5be90
      Parent: 481899b3317624a1a9df5ff202a8ec38b7748baa0bc9d0e4156203b8771ce824
     Subject: fix: binary has (misplaced) AVX512 instructions (d53a8461)
        Date: 2023-12-04 15:15:35 +0000
```

Test it (fallback is working):

```
$ flatpak run com.openwall.John --test=0 --format=sha*

Will run 8 OpenMP threads
Testing: sha1crypt, NetBSD's sha1crypt [PBKDF1-SHA1 256/256 AVX2 8x]... (8xOMP) PASS
Testing: sha256crypt, crypt(3) $5$ (rounds=5000) [SHA256 256/256 AVX2 8x]... (8xOMP) PASS
Testing: sha512crypt, crypt(3) $6$ (rounds=5000) [SHA512 256/256 AVX2 4x]... (8xOMP) PASS
All 3 formats passed self-tests!

```

**Comment by sleepy124** [comment]
well ty its working now but go ddamn its says ETA 19 hours to find my pass code for my zip fike =(

**Pull request merged**
