### PR TITLE
Update runtime to 21.08

### PR DESCRIPTION
**Pull request by hfiguiere**
Runtime 18.08 has been EOL for 2 years.

### CODE REVIEW

**Comment by hfiguiere** [comment]
This is the minimum to get a runtime that is not EOL for 2 years.

**Comment by claudioandre-br** [comment]
> This is the minimum to get a runtime that is not EOL for 2 years.

I'm afraid it's time to EOL john Jumbo 1. So deprecate these flathub packages. 

I'm still not sure how to proceed, anyway, my plan is to delete these packages (the "flathub account") and/or point users to flatpak bundles that upstream offers. 1.9.0 Jumbo 1 is still usable, but it's a bad idea to offer these outdated binaries especially to end users.

Sorry for taking your time.

**Comment by hfiguiere** [comment]
it still is better of offer them with an up to date runtime.

**Comment by claudioandre-br** [comment]
If you think this is a good strategy, we can use it (distributions do the same thing, after all).

**Comment by hfiguiere** [comment]
That's the idea. Same code + 1 patch needed due to invalida code (comes from upstream).

There are unmaintained apps we ship on flathub, because they are unmaintained.

And when there is an update from the app then it can be done.

**Review by claudioandre-br — APPROVED** [review]

**Pull request merged**
